# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Ilonacodes 2018"
license = "All rights reserved"
licenselink = "https://github.com/ilonacodes/ilonacodes.github.io/blob/master/themes/ilonacodes-2018/LICENSE"
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "Ilona Demidenko"
  homepage = "https://ilonacodes.com"
