languageCode = "en-us"
title = "Ilona Who Codes"
baseURL = "//www.ilonacodes.com/"
theme = "ilonacodes-2018"

[params]
	showglobe = false

	highlight = true

	favicon = "favicon.ico"

	analytics = "UA-109315732-1"

	github = "https://github.com/ilonacodes"
	email = "ilona@ilonacodes.com"

	profilepic = "img/ilonapic.jpg"

	title = "Ilona Who Codes"
	subtitle = "Aspiring UI/UX Designer and Front-End Developer"
	location = "Berlin, Germany"

	copyright = "2018 ilonacodes"

	profilePhoto = "/img/ilona_2.jpg"
	profileName = "Ilona who codes"
	profileBio = "Frontend Engineer in Berlin"
	profileLocation = "M.Sc in Media CS"
	profileQuote = '"I like to work hard for things that are worth it."'

[[params.navlinks]]
	title = "ilonacodes"
	url = "/"
	main = true

[[params.navlinks]]
	title = "Blog"
	url = "/blog"

[[params.navlinks]]
	title = "YouTube"
	url = "https://www.youtube.com/channel/UCZHUFhQTMcJVekb6KAqqtkg"

[[params.navlinks]]
	title = "Contact"
	url = "mailto:ilona@ilonacodes.com"

[[params.footer.socialLinks]]
	iconClass = "fab fa-github"
	url = "https://github.com/ilonacodes"

[[params.footer.socialLinks]]
	iconClass = "fab fa-instagram"
	url = "https://instagram.com/ilonacodes"

[[params.footer.socialLinks]]
	iconClass = "fab fa-twitter-square"
	url = "https://twitter.com/ilonacodes"

[[params.footer.socialLinks]]
	iconClass = "fab fa-medium"
	url = "https://medium.com/@ilonacodes"

[[params.footer.socialLinks]]
	iconClass = "fab fa-dribbble"
	url = "https://dribbble.com/ilonacodes"
