languageCode = "en-us"
title = "My New Hugo Site"
baseurl = "//www.ilonacodes.com/"
theme = "hugo-geo-modified"

[params]
	showglobe = false

	favicon = "favicon.ico"

	analytics = "UA-109315732-1"

	github = "https://github.com/ilonacodes"
	email = "demiluri@gmail.com"

	profilepic = "img/ilonapic.jpg"

	title = "Ilona Who Codes"
	subtitle = "Aspiring UI/UX Designer and Front-End Developer"
	location = "Berlin, Germany"

	[[params.navlinks]]
	name = "about me"
	url = "/"

	[[params.navlinks]]
	name = "ilonacodes"
	url = "/"

	[[params.navlinks]]
	name = "read my blog"
	url = "blog"

	# [[params.navlinks]]
	# name = "Contact"
	# url = "contact"
