languageCode = "en-us"
title = "My New Hugo Site"
baseurl = "https://ilonacodes.github.io/"
theme = "hugo-geo-modified"

[params]
	showglobe = false

	favicon = "favicon.ico"

	analytics = "code-here"

	github = "https://github.com/ilonacodes"
	email = "demiluri@gmail.com"

	profilepic = "img/IlonaCodes.jpg"

	title = "Ilona Who Codes"
	subtitle = "Aspiring UI/UX Designer and Front-End Developer"
	location = "Berlin, Germany"

	[[params.navlinks]]
	name = "About"
	url = ""

	[[params.navlinks]]
	name = "Portfolio"
	url = "portfolio"

	[[params.navlinks]]
	name = "Blog"
	url = "blog"

	# [[params.navlinks]]
	# name = "Contact"
	# url = "contact"
