languageCode = "en-us"
title = "Ilona Who Codes & UXs"
baseurl = "//www.ilonacodes.com/"
theme = "ilonacodes-2018"

[params]
	showglobe = false

	highlight = true

	favicon = "favicon.ico"

	analytics = "UA-109315732-1"

	github = "https://github.com/ilonacodes"
	email = "demiluri@gmail.com"

	profilepic = "img/ilonapic.jpg"

	title = "Ilona Who Codes"
	subtitle = "Aspiring UI/UX Designer and Front-End Developer"
	location = "Berlin, Germany"

[[params.navlinks]]
	title = "ilonacodes"
	url = "/"
	main = true

[[params.navlinks]]
	title = "Blog"
	url = "/blog"

[[params.navlinks]]
	title = "Portfolio"
	url = "/ui-ux-projects"

[[params.navlinks]]
	title = "Contact"
	url = "mailto:ilona@ilonacodes.com"
