name = "hugo-geo"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/alexurquhart/hugo-geo/master/LICENSE"
description = "A responsive blog theme made using Bootstrap 3, jQuery, and D3.js"
homepage = "https://alexurquhart.com"
tags = ["blog"]
features = ["blog", "responsive", "bootstrap"]
min_version= 0.14

[author]
    name = "Alex Urquhart"
    email = "alexurquhart@gmail.com"
    url = "https://alexurquhart.com"